function T0_3 = T0_3(rob,in2)
%% T0_3 - Forward kinematics for the three link copy arm up to frame 3 of 3. 
% ========================================================================= 
%    
%    T = T0_3(rob,q) 
%    T = rob.T0_3(q) 
%    
%  Description:: 
%    Given a set of joint variables up to joint number 3 the function 
%    computes the pose belonging to that joint with respect to the base frame. 
%    
%  Input:: 
%    q:  3-element vector of generalized coordinates. 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    T:  [4x4] Homogenous transformation matrix relating the pose of joint 3 of 3 
%              for the given joint values to the base frame. 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also three link copy.
%    
    
% Copyright (C) 1993-2014, by Peter I. Corke 
% Copyright (C) 2012-2014, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 5.6.
%    13-Aug-2014 19:22:43

q1 = in2(:,1);
q2 = in2(:,2);
q3 = in2(:,3);
t19 = cos(q1);
t20 = sin(q2);
t21 = cos(q2);
t22 = sin(q1);
t23 = cos(q3);
t24 = t19.*t20;
t25 = t21.*t22;
t26 = t24+t25;
t27 = sin(q3);
t28 = t19.*t21;
t30 = t20.*t22;
t29 = t28-t30;
t31 = t23.*t29;
t32 = t31-t26.*t27;
t33 = t23.*t26;
t34 = t27.*t29;
T0_3 = reshape([t32,t33+t34,0.0,0.0,-t23.*t26-t27.*t29,t32,0.0,0.0,0.0,0.0,1.0,0.0,t19+t28-t30+t31-t26.*t27,t22+t24+t25+t33+t34,0.0,1.0],[4, 4]);
